[tool.poetry]
name = "gajapathirao"
version = "0.1.0"
description = ""
authors = ["GajapathiRaoAmpera <gajapathi.mugunda@amperatech.ai>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
psycopg = {extras = ["binary"], version = "^3.3.4"}
pandas = "^3.0.5"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
