[tool.poetry]
name = "gajapathirao"
version = "0.1.0"
description = ""
authors = ["GajapathiRaoAmpera <gajapathi.mugunda@amperatech.ai>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
pydantic = "^2.13.5"
psycopg = {extras = ["binary"], version = "^3.3.5"}
fastapi = "^0.141.1"
uvicorn = "^0.52.4"
pathlib = "^1.0.1"
dotenv = "^0.9.9"
passlib = {extras = ["bcrypt"], version = "^1.7.4"}


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
