[tool.poetry]
package-mode = false
name = "genai"
version = "0.1.0"
description = ""
authors = ["deepikaampera <deepika.katam@amperatech.ai>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
notebook = "^7.6.3"
jupyterlab = "^4.6.4"
tiktoken = "^0.14.0"
sentence-transformers = "^6.1.0"
matplotlib = "^3.11.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
