[tool.poetry]
name = "project1"
version = "0.1.0"
description = ""
authors = ["deepikaampera <deepika.katam@amperatech.ai>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
pandas = "^3.0.5"
numpy = "^2.5.2"
matplotlib = "^3.11.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
